// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZRED-WSIr0QJWLCi21hbsOu6KXAr8-Hk',
    appId: '1:706355460380:web:0d21f0816e4264c7fee2d9',
    messagingSenderId: '706355460380',
    projectId: 'quiz-app-92723',
    authDomain: 'quiz-app-92723.firebaseapp.com',
    storageBucket: 'quiz-app-92723.appspot.com',
    measurementId: 'G-JX5SV7MZ10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMAH8Vm1ZnxMJg_UkmEx7bpSs7RHJzXlY',
    appId: '1:706355460380:android:9124487d93d19131fee2d9',
    messagingSenderId: '706355460380',
    projectId: 'quiz-app-92723',
    storageBucket: 'quiz-app-92723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHz8nvS4lkkaeGFFam6jdwQv49n9XS68c',
    appId: '1:706355460380:ios:cc2a8554b76edc9ffee2d9',
    messagingSenderId: '706355460380',
    projectId: 'quiz-app-92723',
    storageBucket: 'quiz-app-92723.appspot.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHz8nvS4lkkaeGFFam6jdwQv49n9XS68c',
    appId: '1:706355460380:ios:9500cc9a3adae240fee2d9',
    messagingSenderId: '706355460380',
    projectId: 'quiz-app-92723',
    storageBucket: 'quiz-app-92723.appspot.com',
    iosBundleId: 'com.example.quiz.RunnerTests',
  );
}
